fn_single_line = false
force_explicit_abi = true
format_macro_bodies = true
format_macro_matchers = true
group_imports = "One"
hard_tabs = false
hex_literal_case = "Lower"
imports_granularity = "Item"
imports_layout = "Horizontal"
merge_derives = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
tab_spaces = 2
trailing_semicolon = true
use_field_init_shorthand = true
wrap_comments = false
