FROM node:21

WORKDIR /app

COPY package.json .npmrc .
ARG GH_PAT
RUN echo "//npm.pkg.github.com/:_authToken=${GH_PAT}" >>.npmrc
RUN npm i

COPY tsconfig.json .
COPY common common
COPY hn-enqueuer hn-enqueuer

CMD ts-node -T hn-enqueuer/main
