# We use `init: true` as Node.js won't respond to signals or process.exit() when PID 1.

services:
  build-data:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/build-data
    init: true
    build:
      context: .
      dockerfile: Dockerfile.build-data
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
    volumes:
      - "/hndr/data:/hndr-data"

  calc-comment-post-ids:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/calc-comment-post-ids
    init: true
    build:
      context: .
      dockerfile: Dockerfile.calc-comment-post-ids
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}

  calc-post-canon-ids:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/calc-post-canon-ids
    init: true
    build:
      context: .
      dockerfile: Dockerfile.calc-post-canon-ids
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
    volumes:
      - "/hndr/data:/hndr-data"

  crawler:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/crawler
    init: true
    build:
      context: .
      dockerfile: Dockerfile.crawler
      args:
        GH_PAT: ${GH_PAT}
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      INFLUXDB_ENDPOINT: ${INFLUXDB_ENDPOINT}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      LOKI_BASICAUTH_PASSWORD: ${LOKI_BASICAUTH_PASSWORD}
      LOKI_BASICAUTH_USER: ${LOKI_BASICAUTH_USER}
      LOKI_ENDPOINT: ${LOKI_ENDPOINT}
      QUEUED_API_KEY: ${QUEUED_API_KEY}

  enqueuer:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/enqueuer
    init: true
    build:
      context: .
      dockerfile: Dockerfile.enqueuer
      args:
        GH_PAT: ${GH_PAT}
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      QUEUED_API_KEY: ${QUEUED_API_KEY}

  umap:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/umap
    init: true
    build:
      context: .
      dockerfile: Dockerfile.umap
    volumes:
      - "/hndr/data:/hndr-data"
