FROM python:3.12

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

ARG MAIN
COPY common common
COPY $MAIN $MAIN

ENV MAIN=$MAIN
ENV PYTHONPATH=/app
# Otherwise nothing is printed.
ENV PYTHONUNBUFFERED=1
CMD python $MAIN/main.py
