FROM rust

WORKDIR /app

COPY Cargo.toml .
COPY common common
COPY calc-post-canon-ids calc-post-canon-ids
RUN cargo build --release --bin calc-post-canon-ids

ENV RUST_BACKTRACE=1
CMD target/release/calc-post-canon-ids
