# We use `init: true` as Node.js won't respond to signals or process.exit() when PID 1.

services:
  als:
    image: wilsonzlin/hndr-python-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.python-base
    environment:
      MAIN: als/main.py
      # OpenBLAS is configured to use 32 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
      OPENBLAS_NUM_THREADS: "1"
    volumes:
      - "${DOCKER_VOLUME_DIR}:/hndr-data"

  build-data:
    image: wilsonzlin/hndr-rust-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.rust-base
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      MAIN: build-data
    volumes:
      - "${DOCKER_VOLUME_DIR}:/hndr-data"

  build-nn-data:
    image: wilsonzlin/hndr-rust-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.rust-base
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      MAIN: build-nn-data
    volumes:
      - "${DOCKER_VOLUME_DIR}:/hndr-data"

  calc-comment-post-ids:
    image: wilsonzlin/hndr-rust-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.rust-base
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      MAIN: calc-comment-post-ids

  calc-post-canon-ids:
    image: wilsonzlin/hndr-rust-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.rust-base
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      MAIN: calc-post-canon-ids
    volumes:
      - "${DOCKER_VOLUME_DIR}:/hndr-data"

  crawler:
    image: wilsonzlin/hndr-crawler
    init: true
    build:
      context: .
      dockerfile: Dockerfile.crawler
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      INFLUXDB_ENDPOINT: ${INFLUXDB_ENDPOINT}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      LOKI_BASICAUTH_PASSWORD: ${LOKI_BASICAUTH_PASSWORD}
      LOKI_BASICAUTH_USER: ${LOKI_BASICAUTH_USER}
      LOKI_ENDPOINT: ${LOKI_ENDPOINT}
      QUEUED_API_KEY: ${QUEUED_API_KEY}

  enqueuer:
    image: wilsonzlin/hndr-enqueuer
    init: true
    build:
      context: .
      dockerfile: Dockerfile.enqueuer
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      QUEUED_API_KEY: ${QUEUED_API_KEY}

  kmeans:
    image: wilsonzlin/hndr-python-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.python-base
    environment:
      MAIN: kmeans/main.py
    volumes:
      - "${DOCKER_VOLUME_DIR}:/hndr-data"

  umap:
    image: wilsonzlin/hndr-python-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.python-base
    environment:
      MAIN: umap/main.py
    volumes:
      - "${DOCKER_VOLUME_DIR}:/hndr-data"
