FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

ARG MAIN
COPY common common
COPY $MAIN $MAIN

ENV MAIN=$MAIN
# Otherwise nothing is printed.
ENV PYTHONUNBUFFERED=0
CMD python $MAIN/main.py
