FROM rust

WORKDIR /app

COPY Cargo.toml .
COPY common common
COPY calc-comment-post-ids calc-comment-post-ids
RUN cargo build --release --bin calc-comment-post-ids

ENV RUST_BACKTRACE=1
CMD target/release/calc-comment-post-ids
