FROM python:3.12

RUN pip install sentence_transformers
RUN python -c 'from sentence_transformers import SentenceTransformer; SentenceTransformer("jinaai/jina-embeddings-v2-small-en")'

ARG MAIN
ENV MAIN=$MAIN

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY common common
COPY $MAIN $MAIN

WORKDIR /app/$MAIN
ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1
CMD uvicorn main:app --host 0.0.0.0 --log-level warning --port $PORT
