FROM python:3.12

ARG MAIN
ENV MAIN=$MAIN

RUN pip install huggingface_hub
COPY $MAIN/download_model.py /tmp/download_model.py
RUN python /tmp/download_model.py

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY common common
COPY $MAIN $MAIN

WORKDIR /app/$MAIN
ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1
CMD uvicorn main:app --host 0.0.0.0 --log-level warning --port $PORT
