FROM rust:1.77-slim-bookworm

RUN apt -y update && apt -yq install libssl-dev pkg-config

WORKDIR /app

ARG MAIN
COPY Cargo.toml .
COPY common common
COPY $MAIN $MAIN
RUN cargo build --release --bin $MAIN

FROM debian:bookworm-slim

ARG MAIN
COPY --from=0 /app/target/release/$MAIN /main

RUN apt -y update && apt -yq install ca-certificates openssl && rm -rf /var/lib/apt/lists/*

ENV RUST_BACKTRACE=1
ENV RUST_LOG=info
CMD /main
