# We use `init: true` as Node.js won't respond to signals or process.exit() when PID 1.

services:
  build-data:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/rust-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.rust-base
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      MAIN: build-data
    volumes:
      - "${DOCKER_VOLUME_DIR}:/hndr-data"

  calc-comment-post-ids:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/rust-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.rust-base
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      MAIN: calc-comment-post-ids

  calc-post-canon-ids:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/rust-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.rust-base
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      MAIN: calc-post-canon-ids
    volumes:
      - "${DOCKER_VOLUME_DIR}:/hndr-data"

  crawler:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/crawler
    init: true
    build:
      context: .
      dockerfile: Dockerfile.crawler
      args:
        GH_PAT: ${GH_PAT}
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      INFLUXDB_ENDPOINT: ${INFLUXDB_ENDPOINT}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      LOKI_BASICAUTH_PASSWORD: ${LOKI_BASICAUTH_PASSWORD}
      LOKI_BASICAUTH_USER: ${LOKI_BASICAUTH_USER}
      LOKI_ENDPOINT: ${LOKI_ENDPOINT}
      QUEUED_API_KEY: ${QUEUED_API_KEY}

  enqueuer:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/enqueuer
    init: true
    build:
      context: .
      dockerfile: Dockerfile.enqueuer
      args:
        GH_PAT: ${GH_PAT}
    environment:
      DB_RPC_API_KEY: ${DB_RPC_API_KEY}
      QUEUED_API_KEY: ${QUEUED_API_KEY}

  kmeans:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/python-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.python-base
    environment:
      MAIN: kmeans/main.py
    volumes:
      - "${DOCKER_VOLUME_DIR}:/hndr-data"

  umap:
    image: us-ashburn-1.ocir.io/sd58faummalr/hndr/python-base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.python-base
    environment:
      MAIN: umap/main.py
    volumes:
      - "${DOCKER_VOLUME_DIR}:/hndr-data"
